config/routes.rb
Rails.application.routes.draw do
devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
# devise_for :users
  root to: 'messages#index'

  resources :messages
end

app/models/message.rb
class Message < ActiveRecord::Base
  before_create :send_message

  private

    def send_message
      begin
        response = RestClient::Request.new(
          :method => :post,
          :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
          :user => ENV['TWILIO_ACCOUNT_SID'],
          :password => ENV['TWILIO_AUTH_TOKEN'],
          :payload => { :Body => body,
                        :To => to,
                        :From => from }
          ).execute
      rescue RestClient::BadRequest => error
        message = JSON.parse(error.response)['message']
        errors.add(:base, message)
        false
      end
    end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
before_filter :authenticate_user!, except: [:index, :show]

  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      flash[:notice] = "Successful"
      redirect_to messages_path
    else
      render 'new'
    end
  end


private

  def message_params
      params.require(:message).permit(:to, :from, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %>
<% end %>
<%= yield %>

<div id='flash_notice'>
    <% if flash[:notice] == 'Successful' %>
      <div class='alert alert-success' role='alert'>
        <%= flash[:notice] %></div>
    <% elsif flash[:notice] != nil %>
      <div class='alert alert-info' role='alert'>
        <%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] != nil %>
      <div class='alert alert-danger' role='alert'>
        <%= flash[:alert] %></div>
    <% end %>
  </div>
</body>
</html>

app/views/messages/index.html.erb
<% content_for(:title, "Messaging Shmessaging" ) %>
<div class="container-fluid">

<div class="row">
  <div class="heading col-xs-9">
    <h2>Messages</h2>
  </div>
  <div class="heading col-xs-3">
    <h2><%= link_to "Add New Message", new_message_path, :class => "addnew" %></h2>
  </div>
</div>

<div class="col-xs-12 messages-body">
  <% @messages.each do |message| %>
    <div class="messagebox">
      <div class="message-each">From: <span class="message-each-body"><%= message.from %></span></div>
      <div class="message-each">To: <span class="message-each-body"><%= message.to %></span></div>
      <div class="message-each">Message: <span class="message-each-body"><%= message.body %></span></div>
    </div>
  <% end %>
</div>

</div>

app/views/messages/new.html.erb
<% content_for(:title, "New Message" ) %>

<div class="heading">
  <h2>New Message</h2>
</div>

<% if @message.errors.any? %>
  <% @message.errors.full_messages.each do |message| %>
    <% flash[:alert] = message %>
  <% end %>
<% end%>

<div class="form-group">
  <%= form_for @message do |f| %>
  <%= f.label :to %>
  <%= f.text_field :to %>
  <%= f.label :from %>
  <%= f.text_field :from %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.submit(:class =>"btn btn-primary") %>
  </div>
<% end %>